<template>
  <FormPage>
    <iframe
      src="https://docs.google.com/forms/d/e/1FAIpQLScJvlGl_lMqk1j3shJ4ykmL4bW0jkPlHwLi1PQQDCnK1Dxu_w/viewform?embedded=true"
      width="100%"
      height="1200px"
      frameborder="0"
      marginheight="0"
      marginwidth="0"
    >
      Loading…
    </iframe>
  </FormPage>
</template>
