<template>
  <FormPage>
    <iframe
      src="https://docs.google.com/forms/d/e/1FAIpQLScI2PhRmpS6kYgBajPBKJsweGrnle0IuxiJvrcOF4_gIQk_qQ/viewform?embedded=true"
      width="100%"
      height="1200px"
      frameborder="0"
      marginheight="0"
      marginwidth="0"
    >
      Loading…
    </iframe>
  </FormPage>
</template>
