name: Test and Build React

on:
    push:

    pull_request:
        branches: ['main']

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  cache: 'npm'

            - run: npm ci

            # Build before format so that if errors exist in both the error that shows up is a build error and not a format error
            - name: Build app
              run: npm run build

            - name: Prettier check
              run: npm run format:check
